# Generated by Django 5.0.1 on 2024-03-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contactnumber', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('taskname', models.CharField(max_length=50)),
                ('taskstatus', models.CharField(max_length=50)),
            ],
        ),
    ]
