# Generated by Django 5.0.1 on 2024-03-20 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='services',
            new_name='servicess',
        ),
    ]
